### PR TITLE
Update config to enable Bintray uploads

### PR DESCRIPTION
**Pull request by rogerhu**
Shared POM config between Bintray and Sonatype

### CODE REVIEW

**Comment by mmimeault** [comment]
Auto deploy to bintray?
We should put the commands in the README to help. Or this will be done automatically on travis?

**Comment by rogerhu** [comment]
Auto deploy isn't setup just yet.  I'm doing this first to validate setup.

**Comment by jhansche** [comment]
So this is still broken?  Travis is reporting that it is still not uploading because of the org change, as recently as 24 hours ago:

https://travis-ci.org/parse-community/ParseLiveQuery-Android/builds/229764414

    $ ./scripts/publish_snapshot.sh
    Skipping publishing SNAPSHOT: wrong repository. Expected 'ParsePlatform/ParseLiveQuery-Android' but was 'parse-community/ParseLiveQuery-Android'

I see that `1.0.3` is available in jcenter, and I see that it includes my recent fix for #48.  Was that just released manually, instead of via Travis?

**Comment by rogerhu** [comment]
Correct I manually released it.   I'll go fix this snapshot issue.

**Pull request merged**
